export const AGREGAR_MASCOTA ="AGREGAR_MASCOTA"
export const AGREGAR_MASCOTA_EXITO ="AGREGAR_MASCOTA_EXITO"
export const AGREGAR_MASCOTA_ERROR ="AGREGAR_MASCOTA_ERROR"

export const DESCARGA_MASCOTAS ="DESCARGA_MASCOTAS"
export const DESCARGA_MASCOTAS_EXITO ="DESCARGA_MASCOTAS_EXITO"
export const DESCARGA_MASCOTAS_ERROR ="DESCARGA_MASCOTAS_ERROR"

export const ELIMINAR_MASCOTA ="ELIMINAR_MASCOTA"
export const ELIMINAR_MASCOTA_EXITO ="ELIMINAR_MASCOTA_EXITO"
export const ELIMINAR_MASCOTA_ERROR ="ELIMINAR_MASCOTA_ERROR"

export const OBTENER_MASCOTA_EDITAR ="OBTENER_MASCOTA_EDITAR"
export const EDITAR_MASCOTA ="EDITAR_MASCOTA"
export const EDITAR_MASCOTA_EXITO ="EDITAR_MASCOTA_EXITO"
export const EDITAR_MASCOTA_ERROR ="EDITAR_MASCOTA_ERROR"

export const  MOSTRAR_ALERTA ="MOSTRAR_ALERTA"
export const OCULTAR_ALERTA ="OCULTAR_ALERTA" 