export const AGREGAR_MASCOTA ="AGREGAR_MASCOTA"
export const AGREGAR_MASCOTA_EXITO ="AGREGAR_MASCOTA_EXITO"
export const AGREGAR_MASCOTA_ERROR ="AGREGAR_MASCOTA_ERROR"

export const DESCARGA_MASCOTAS ="DESCARGA_MASCOTAS"
export const DESCARGA_MASCOTAS_EXITO ="DESCARGA_MASCOTAS_EXITO"
export const DESCARGA_MASCOTAS_ERROR ="DESCARGA_MASCOTAS_ERROR"
