export const AGREGAR_MASCOTA ="AGREGAR_MASCOTA"
export const AGREGAR_MASCOTA_EXITO ="AGREGAR_MASCOTA_EXITO"
export const AGREGAR_MASCOTA_ERROR ="AGREGAR_MASCOTA_ERROR"

export const DESCARGA_MASCOTAS ="DESCARGA_MASCOTAS"
export const DESCARGA_MASCOTAS_EXITO ="DESCARGA_MASCOTAS_EXITO"
export const DESCARGA_MASCOTAS_ERROR ="DESCARGA_MASCOTAS_ERROR"

export const ELIMINAR_MASCOTA ="ELIMINAR_MASCOTA"
export const ELIMINAR_MASCOTA_EXITO ="ELIMINAR_MASCOTA_EXITO"
export const ELIMINAR_MASCOTA_ERROR ="ELIMINAR_MASCOTA_ERROR"

